# Generated by Django 3.1.5 on 2021-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
